name: inspector_tps
description: "tps"
publish_to: 'none'
version: 0.0.1+42

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  go_router: ^14.0.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  get_it: ^7.7.0
  flutter_redux: ^0.10.0
  json_annotation: ^4.9.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  equatable: ^2.0.5
  intl: ^0.19.0
  sqflite: ^2.3.3
  path: ^1.9.0
  camera: ^0.11.0+2
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.0.3
  flutter_typeahead: ^5.2.0

dev_dependencies:
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9


flutter_native_splash:
  background_image: assets/splash.png
  android_12:
    color: "#5E35B1"
    image: assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#5E35B1"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/